# Generated by Django 5.0.4 on 2024-04-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
    ]
